pipeline {
    agent { node {label 'mvn'}}

   stages {
       stage('Prebuild'){
           steps {
               echo "Prepare to build"
               sh 'pwd'
               dir('./Java'){
                   sh 'mvn clean'
               }
           }
       }
       stage('Test'){
           steps {
               echo "testing......"
               dir('./Java'){
                   sh 'mvn test'
               }
           }
       }
   }
}