pipeline {
    agent { node {label 'mvn'}}

   stages {
       stage('Prebuild'){
           steps {
               echo "Start prepare to build"
               sh 'pwd'
               sh 'mvn --version'
               sh 'java -version'
           }
       }
       stage('Build'){
           steps {
               echo "build......"
           }
       }
       stage('Testing'){
           steps {
               echo "Testing......"
           }
       }
   }
}