pipeline {
    agent { node {label 'mvn'}}

   stages {
       stage('Prebuild'){
           steps {
               echo "Start prepare to build"
           }
       }
       stage('Build'){
           steps {
               echo "build......"
           }
       }
       stage('Testing'){
           steps {
               echo "Testing......"
           }
       }
   }
}